### ISSUE TITLE
Do I need an AWS account to start the server?

### ISSUE THREAD

**Issue by FerJSsilva** [j3camero/scum-zone#4]
Trying to run the update script as recommended but it's not working.
Receiving an error about timeout on connection:

`D:\DevHomeProjects\github\scum-zone\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)`

Can someone help me to do the initial configuration? I am willing to update documentation afterward; Thanks

**Comment by j3camero** [comment]
Yes! The script stores the kill data in AWS DynamoDB. But it's free ($$)!

AWS allows you to use an appreciable amount of DynamoDB without incurring any cost. You may still need to give AWS your credit card, but pretty sure you can run these scripts for free.

I recommend running all these scripts on an AWS EC2 node hosted by AWS. Then the DynamoDB permissions automatically "just work" so you can skip the difficult configuration step.

**Comment by AlexisPrieto** [comment]
if the data is stored on AWS should we have the tables created? Or do we have a script to create them or BD Model to help us?

I have connected my AWS account with the app, but I am getting a ResourceNotFoundException since the tables do not exist.

error:
PS F:\Desarrollo\scum-zone-master\scum-zone-master> node update.js
Checking for a running event.
F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^
ResourceNotFoundException: Requested resource not found
    at Request.extractError (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\protocol\json.js:51:27)
    at Request.callListeners (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (F:\Desarrollo\scum-zone-master\scum-zone-master\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'ResourceNotFoundException',
  time: 2020-08-07T15:33:44.164Z,
  requestId: '8PM6TM9O0SHF2M30BS4HVHU5C3VV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 31.32955984026202

Can someone help me?
