### ISSUE TITLE
Missing credentuals in config

### ISSUE THREAD

**Issue by G-Dolan** [j3camero/scum-zone#5]
Hi, 

I am just trying to set this up however I am getting the error;

Checking for a running event.
/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

CredentialsError: Missing credentials in config
    at IncomingMessage.<anonymous> (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/util.js:888:34)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Is there a specific version of aws-sdk that should be getting used?

Cheers

**Comment by G-Dolan** [comment]
I have managed to run the update by using a newer version of Node however when launching I am still receiving a stack so I suspect it's not actually worked. 

Serving on port 81


Error: ENOENT: no such file or directory, open 'public/update.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at loadUpdateData (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/server.js:22:29)
    at app.get (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/server.js:28:18)
    at Layer.handle [as handle_request] (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/express/lib/router/index.js:335:12)

**Comment by G-Dolan** [comment]
Apologies for the spam, running through issues as they come, I believe it's now failing to contact and create the database;

:/var/www/vhosts/scumsofanarchy.com/scum-zone$ node update.js
Checking for a running event.
/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

ResourceNotFoundException: Requested resource not found
    at Request.extractError (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/mnt/data/vhosts/scumsofanarchy.com/scum-zone/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

The API details I am using have full admin rights so I am not sure why it's saying no.

**Comment by AlexisPrieto** [comment]
I have the same error, the AWS credentials are correct and I am able to connect to AWS, but update.js fails to create the tables in DynamoDB. although I'm not sure if any file is responsible for creating the tables in aws.
